# Generated by Django 5.2.6 on 2025-09-16 11:55

import django.contrib.postgres.fields
import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons_sailings', '0001_initial'),
        ('ships_cabins', '0004_remove_shipcurrency_currency_format_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('non_refundable', models.BooleanField(db_default=False, default=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveSetting',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('max_hold_minutes', models.IntegerField(db_default=2880, default=2880)),
                ('reminder_scheduled_minutes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_default='{2880, 1440}', default=list, size=None)),
                ('allow_extensions', models.BooleanField(db_default=True, default=True)),
                ('max_extensions', models.IntegerField(db_default=1, default=1)),
                ('extension_minutes', models.IntegerField(db_default=1440, default=1440)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('uc_ref', models.TextField()),
                ('snapshot', models.JSONField()),
                ('idempotency_key', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ships_cabins.cabin')),
                ('sailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons_sailings.sailing')),
            ],
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('uc_ref', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('expired', 'Expired'), ('converted', 'Converted')], db_default='active', default='active', max_length=9)),
                ('idempotency_key', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ships_cabins.cabin')),
                ('sailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons_sailings.sailing')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseRequest',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling.hold')),
            ],
        ),
        migrations.CreateModel(
            name='CancellationPolicyTier',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('min_days', models.IntegerField()),
                ('max_days', models.IntegerField()),
                ('charge_type', models.CharField(choices=[('percent_total', 'Percent Total'), ('percent_cos', 'Percent COS'), ('fixed_amount', 'Fixed Amount')], max_length=13)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling.cancellationpolicy')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('min_days__lte', models.F('max_days'))), name='ck_days_order')],
            },
        ),
    ]
