# Generated by Django 5.2.6 on 2025-09-13 11:16

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_pg_enumerated_types'),
        ('routes', '0002_alter_route_created_at_alter_route_id_and_more'),
        ('ships_cabins', '0003_alter_cabin_created_at_alter_cabin_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('default_margin_b2b', models.DecimalField(decimal_places=4, max_digits=6)),
                ('default_margin_b2c', models.DecimalField(decimal_places=4, max_digits=6)),
                ('is_archived', models.BooleanField(db_default=False, default=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonShip',
            fields=[
                ('pk', models.CompositePrimaryKey('season_id', 'ship_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons_sailings.season')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ships_cabins.ship')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='ships',
            field=models.ManyToManyField(related_name='season_ships', through='seasons_sailings.SeasonShip', to='ships_cabins.ship'),
        ),
        migrations.CreateModel(
            name='Sailing',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('departure_date', models.DateField()),
                ('nights', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.route')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ships_cabins.ship')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='seasons_sailings.season')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('nights__gt', 0)), name='nights_nonempty')],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='season_nonempty'),
        ),
    ]
