# Generated by Django 5.2.6 on 2025-09-18 12:03

import common.functions
import django.contrib.postgres.functions
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_pg_enumerated_types')
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('is_active', models.BooleanField(db_default=True)),
                ('created_at', models.DateTimeField(db_default=common.functions.TxNow())),
                ('updated_at', models.DateTimeField(db_default=common.functions.TxNow())),
            ],
            options={
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='CabinCategory',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('sort_order', models.IntegerField(db_default=100)),
                ('is_active', models.BooleanField(db_default=True)),
                ('created_at', models.DateTimeField(db_default=common.functions.TxNow())),
                ('updated_at', models.DateTimeField(db_default=common.functions.TxNow())),
            ],
            options={
                'db_table': 'cabin_categories',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(db_default=common.functions.TxNow())),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='amenity',
            trigger=pgtrigger.compiler.Trigger(name='trg_amenities_updated', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n        BEGIN\n            NEW.updated_at := NOW();\n            RETURN NEW;\n        END;\n        ', hash='db09774fca991f17e3bf9692a7a5b7332301e6c2', operation='UPDATE', pgid='pgtrigger_trg_amenities_updated_389db', table='amenities', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cabincategory',
            trigger=pgtrigger.compiler.Trigger(name='trg_cabin_cat_updated', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n        BEGIN\n            NEW.updated_at := NOW();\n            RETURN NEW;\n        END;\n        ', hash='43a398455505772a111acb41bee6fd6a39924349', operation='UPDATE', pgid='pgtrigger_trg_cabin_cat_updated_74006', table='cabin_categories', when='BEFORE')),
        ),
    ]
