# Generated by Django 5.2.6 on 2025-09-25 14:50

import common.functions
import django.contrib.postgres.functions
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_enable_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinCategory',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sort_order', models.IntegerField(db_default=100)),
                ('is_active', models.BooleanField(db_default=True)),
                ('created_at', models.DateTimeField(db_default=common.functions.TxNow())),
                ('updated_at', models.DateTimeField(db_default=common.functions.TxNow())),
            ],
            options={
                'db_table': 'cabin_categories',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(db_default=common.functions.TxNow())),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_active', models.BooleanField(db_default=True)),
                ('created_at', models.DateTimeField(db_default=common.functions.TxNow())),
                ('updated_at', models.DateTimeField(db_default=common.functions.TxNow())),
            ],
            options={
                'db_table': 'amenities',
                'constraints': [models.UniqueConstraint(fields=('name',), name='amenities_name_key')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='amenity',
            trigger=pgtrigger.compiler.Trigger(name='trg_amenities_updated', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                NEW.updated_at := NOW();\n                RETURN NEW;\n            END;\n            ', hash='80262dd2f55fb7edd8eeb90733d42a0bb8c4ef1c', operation='UPDATE', pgid='pgtrigger_trg_amenities_updated_389db', table='amenities', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='cabincategory',
            constraint=models.UniqueConstraint(fields=('name',), name='cabin_categories_name_key'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cabincategory',
            trigger=pgtrigger.compiler.Trigger(name='trg_cabin_cat_updated', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                NEW.updated_at := NOW();\n                RETURN NEW;\n            END;\n            ', hash='859cc808c1b608e9bda6cbd0d1a2f06edd1fa013', operation='UPDATE', pgid='pgtrigger_trg_cabin_cat_updated_74006', table='cabin_categories', when='BEFORE')),
        ),
    ]
