# Generated by Django 5.2.6 on 2025-09-10 03:07

import django.contrib.postgres.functions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_pg_enumerated_types')
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CabinCategory',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
