# Generated by Django 5.2.6 on 2025-09-11 12:00

import django.contrib.postgres.functions
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='id',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cabincategory',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cabincategory',
            name='id',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cabincategory',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='cabincategory',
            name='sort_order',
            field=models.IntegerField(db_default=100, default=100),
        ),
        migrations.AlterField(
            model_name='cabincategory',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
    ]
