# Generated by Django 5.2.6 on 2025-09-14 11:16

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0002_alter_amenity_created_at_alter_amenity_id_and_more'),
        ('seasons_sailings', '0001_initial'),
        ('ships_cabins', '0004_remove_shipcurrency_currency_format_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCost',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('key', models.TextField(unique=True)),
                ('label', models.TextField()),
                ('status', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=7)),
                ('applies_to', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=9)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ShipCustomCost',
            fields=[
                ('pk', models.CompositePrimaryKey('ship_id', 'custom_cost_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('custom_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.customcost')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships_cabins.ship')),
            ],
        ),
        migrations.AddField(
            model_name='customcost',
            name='ships',
            field=models.ManyToManyField(related_name='ship_custom_costs', through='pricing.ShipCustomCost', to='ships_cabins.ship'),
        ),
        migrations.CreateModel(
            name='CabinCostOverride',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('base_per_pax', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('single_multiplier', models.DecimalField(db_default=1.5, decimal_places=4, default=1.5, max_digits=6)),
                ('notes', models.TextField()),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ships_cabins.cabin')),
                ('sailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons_sailings.sailing')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='override_currency_format_check'), models.CheckConstraint(condition=models.Q(('single_multiplier__gte', 1.0)), name='override_single_multiplier_validity_check'), models.UniqueConstraint(fields=('sailing', 'cabin'), name='unique_sailing_cabin')],
            },
        ),
        migrations.CreateModel(
            name='CabinCostCustom',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('percent', models.DecimalField(decimal_places=4, max_digits=6)),
                ('currency', models.CharField(max_length=3)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ships_cabins.cabin')),
                ('sailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons_sailings.sailing')),
                ('custom_cost', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pricing.customcost')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='cabin_cost_format_check'), models.CheckConstraint(condition=models.Q(models.Q(('value__isnull', False), ('percent__isnull', True)), models.Q(('value__isnull', True), ('percent__isnull', False)), _connector='OR'), name='ck_custom_value'), models.UniqueConstraint(fields=('sailing', 'cabin', 'custom_cost'), name='unique_sailing_cabin_custom_cost')],
            },
        ),
        migrations.CreateModel(
            name='SeasonShipCost',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('deck', models.TextField()),
                ('base_per_pax', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('single_multiplier', models.DecimalField(db_default=1.5, decimal_places=4, default=1.5, max_digits=6)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.cabincategory')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons_sailings.season')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships_cabins.ship')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='ship_cost_currency_format_check'), models.CheckConstraint(condition=models.Q(('single_multiplier__gte', 1.0)), name='ship_cost_multiplier_validity_check')],
            },
        ),
    ]
