# Generated by Django 5.2.6 on 2025-09-21 17:56

import common.fields
import common.functions
import django.contrib.postgres.functions
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('seasons_sailings', '0001_initial'),
        ('ships_cabins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCost',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('key', models.TextField()),
                ('label', models.TextField()),
                ('mode', common.fields.PostgresEnumField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], enum_type='custom_cost_mode')),
                ('applies_to', common.fields.PostgresEnumField(choices=[('per_cabin', 'Per Cabin'), ('per_pax', 'Per Pax')], enum_type='custom_cost_applies_to')),
                ('is_active', models.BooleanField(db_default=True)),
                ('created_at', models.DateTimeField(db_default=common.functions.TxNow())),
            ],
            options={
                'db_table': 'custom_costs',
            },
        ),
        migrations.CreateModel(
            name='CabinCostCustom',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('percent', models.DecimalField(decimal_places=4, max_digits=6)),
                ('currency', models.CharField(max_length=3)),
                ('cabin', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, to='ships_cabins.cabin')),
                ('sailing', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='seasons_sailings.sailing')),
                ('custom_cost', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, to='pricing.customcost')),
            ],
            options={
                'db_table': 'cabin_cost_customs',
            },
        ),
        migrations.CreateModel(
            name='SeasonShipCost',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('deck', models.TextField(null=True)),
                ('base_per_pax', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('single_multiplier', models.DecimalField(db_default=1.5, decimal_places=4, max_digits=6)),
                ('created_at', models.DateTimeField(db_default=common.functions.TxNow())),
                ('category', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.cabincategory')),
                ('season', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='seasons_sailings.season')),
                ('ship', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='ships_cabins.ship')),
            ],
            options={
                'db_table': 'season_ship_costs',
            },
        ),
        migrations.CreateModel(
            name='ShipCustomCost',
            fields=[
                ('pk', models.CompositePrimaryKey('ship_id', 'custom_cost_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('custom_cost', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='pricing.customcost')),
                ('ship', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='ships_cabins.ship')),
            ],
            options={
                'db_table': 'ship_custom_costs',
            },
        ),
        migrations.AddField(
            model_name='customcost',
            name='ships',
            field=models.ManyToManyField(related_name='ship_custom_costs', through='pricing.ShipCustomCost', to='ships_cabins.ship'),
        ),
        migrations.CreateModel(
            name='CabinCostOverride',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('base_per_pax', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('single_multiplier', models.DecimalField(db_default=1.5, decimal_places=4, max_digits=6)),
                ('notes', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(db_default=common.functions.TxNow())),
                ('cabin', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, to='ships_cabins.cabin')),
                ('sailing', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='seasons_sailings.sailing')),
            ],
            options={
                'db_table': 'cabin_cost_overrides',
                'constraints': [models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='cabin_cost_overrides_currency_check'), models.CheckConstraint(condition=models.Q(('single_multiplier__gte', models.Value(1.0))), name='cabin_cost_overrides_single_multiplier_check'), models.UniqueConstraint(fields=('sailing', 'cabin'), name='cabin_cost_overrides_sailing_id_cabin_id_key')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cabincostoverride',
            trigger=pgtrigger.compiler.Trigger(name='trg_cabin_cost_ovr_updated', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                NEW.updated_at := NOW();\n                RETURN NEW;\n            END;\n            ', hash='c29a97382cc2e8a46c0e51244a8acac16165fc92', operation='UPDATE', pgid='pgtrigger_trg_cabin_cost_ovr_updated_6db93', table='cabin_cost_overrides', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='cabincostcustom',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='cabin_cost_customs_currency_check'),
        ),
        migrations.AddConstraint(
            model_name='cabincostcustom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value__isnull', False), ('percent__isnull', True)), models.Q(('value__isnull', True), ('percent__isnull', False)), _connector='OR'), name='ck_custom_value'),
        ),
        migrations.AddConstraint(
            model_name='cabincostcustom',
            constraint=models.UniqueConstraint(fields=('sailing', 'cabin', 'custom_cost'), name='cabin_cost_customs_sailing_id_cabin_id_custom_cost_id_key'),
        ),
        migrations.AddIndex(
            model_name='seasonshipcost',
            index=models.Index(fields=['season', 'ship', 'category'], name='idx_ssc_lookup'),
        ),
        migrations.AddConstraint(
            model_name='seasonshipcost',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='season_ship_costs_currency_check'),
        ),
        migrations.AddConstraint(
            model_name='seasonshipcost',
            constraint=models.CheckConstraint(condition=models.Q(('single_multiplier__gte', models.Value(1.0))), name='season_ship_costs_single_multiplier_check'),
        ),
        migrations.AddConstraint(
            model_name='customcost',
            constraint=models.UniqueConstraint(fields=('key',), name='custom_costs_key_key'),
        ),
    ]
