# Generated by Django 5.2.6 on 2025-09-16 01:48

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_pg_enumerated_types'),
        ('catalogs', '0002_alter_amenity_created_at_alter_amenity_id_and_more'),
        ('seasons_sailings', '0001_initial'),
        ('ships_cabins', '0004_remove_shipcurrency_currency_format_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('kind', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], max_length=7)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('channel', models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('both', 'Both')], db_default='b2b', default='b2b', max_length=4)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('min_margin_b2b', models.DecimalField(db_default=0.05, decimal_places=4, default=0.05, max_digits=6)),
                ('min_margin_b2c', models.DecimalField(db_default=0.1, decimal_places=4, default=0.1, max_digits=6)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_default='scheduled', default='scheduled', max_length=9)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountTarget',
            fields=[
                ('target_kind', models.TextField()),
                ('pk', models.CompositePrimaryKey('discount_id', 'target_kind', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships_cabins.cabin')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.cabincategory')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.discount')),
                ('sailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons_sailings.sailing')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cabin__isnull', True), ('category__isnull', True), ('sailing__isnull', False)), models.Q(('cabin__isnull', True), ('category__isnull', False), ('sailing__isnull', True)), models.Q(('cabin__isnull', False), ('category__isnull', True), ('sailing__isnull', True)), _connector='OR'), name='ck_target_exactly_one')],
            },
        ),
    ]
