# Generated by Django 5.2.6 on 2025-09-26 00:23

import common.fields
import common.functions
import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('seasons_sailings', '0001_initial'),
        ('ships_cabins', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('kind', common.fields.PostgresEnumField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], enum_type='discount_kind')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('channel', common.fields.PostgresEnumField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('both', 'Both')], db_default='both', enum_type='sales_channel')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('min_margin_b2b', models.DecimalField(db_default=0.05, decimal_places=4, max_digits=6)),
                ('min_margin_b2c', models.DecimalField(db_default=0.1, decimal_places=4, max_digits=6)),
                ('status', common.fields.PostgresEnumField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_default='scheduled', enum_type='discount_status')),
                ('created_at', models.DateTimeField(db_default=common.functions.TxNow())),
                ('created_by', models.ForeignKey(db_column='created_by', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='DiscountTarget',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('target_kind', models.TextField(choices=[('sailing', 'sailing'), ('category', 'category'), ('cabin', 'cabin')])),
                ('target_id', models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('cabin_id'), models.F('category_id'), models.F('sailing_id')), output_field=models.UUIDField())),
                ('cabin', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ships_cabins.cabin')),
                ('category', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.cabincategory')),
                ('discount', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='discounts.discount')),
                ('sailing', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='seasons_sailings.sailing')),
            ],
            options={
                'db_table': 'discount_targets',
                'constraints': [models.CheckConstraint(condition=models.Q(('target_kind__in', ['sailing', 'category', 'cabin'])), name='discount_targets_target_kind_check'), models.CheckConstraint(condition=models.Q(models.Q(('target_kind', 'sailing'), ('cabin__isnull', True), ('category__isnull', True), ('sailing__isnull', False)), models.Q(('target_kind', 'category'), ('cabin__isnull', True), ('category__isnull', False), ('sailing__isnull', True)), models.Q(('target_kind', 'cabin'), ('cabin__isnull', False), ('category__isnull', True), ('sailing__isnull', True)), _connector='OR'), name='ck_target_exactly_one'), models.UniqueConstraint(fields=('discount', 'target_kind', 'target_id'), name='discount_targets_discount_id_target_kind_target_id_key')],
            },
        ),
    ]
