# Generated by Django 5.2.6 on 2025-09-20 20:42

from django.db import migrations
from django.contrib.postgres.operations import CryptoExtension, CITextExtension, BtreeGistExtension


class Migration(migrations.Migration):
    """Prerequisites & Extensions"""

    dependencies = [
    ]

    operations = [
        CryptoExtension(),     # -- gen_random_uuid()
        migrations.RunSQL(     # -- case-insensitive email using collation (citext obsolete)
            """
            CREATE COLLATION IF NOT EXISTS case_insensitive (
                provider = icu,
                locale = 'und-u-ks-level2',
                deterministic = false
            );
            """,
            reverse_sql="""
            DROP COLLATION IF EXISTS case_insensitive;
            """
        ),
        BtreeGistExtension(),  # -- EXCLUDE (uuid WITH =) + ranges
    ]
