# Generated by Django 5.2.6 on 2025-09-17 02:04

from django.db import migrations

# This migration creates PostgreSQL enumerated types used in the application.
# It is Postgres specific and will need adjustments for other databases.
class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        # -- User & security
        migrations.RunSQL(
            """
            DO $$ BEGIN
                CREATE TYPE user_status AS ENUM ('active','suspended');
            EXCEPTION WHEN duplicate_object THEN NULL; END $$;
            """,
            reverse_sql="""
            DROP TYPE IF EXISTS user_status;
            """
        ),
        # -- Map / Content lifecycle
        migrations.RunSQL(
            """
            DO $$ BEGIN
                CREATE TYPE map_status AS ENUM ('draft','active','archived');
            EXCEPTION WHEN duplicate_object THEN NULL; END $$;
            """,
            reverse_sql="""
            DROP TYPE IF EXISTS map_status;
            """
        ),
        # -- Selling life cycles
        migrations.RunSQL(
            """
            DO $$ BEGIN
                CREATE TYPE hold_status AS ENUM ('active','released','expired','converted');
                CREATE TYPE booking_status AS ENUM ('active','cancelled');
            EXCEPTION WHEN duplicate_object THEN NULL; END $$;
            """,
            reverse_sql="""
            DROP TYPE IF EXISTS hold_status;
            DROP TYPE IF EXISTS booking_status;
            """
        ),
        # -- Discounts & channels
        migrations.RunSQL(
            """
            DO $$ BEGIN
                CREATE TYPE discount_kind AS ENUM ('percent','fixed');
                CREATE TYPE discount_status AS ENUM ('scheduled','active','ended','cancelled');
                CREATE TYPE sales_channel AS ENUM ('b2b','b2c','both');
            EXCEPTION WHEN duplicate_object THEN NULL; END $$;
            """,
            reverse_sql="""
            DROP TYPE IF EXISTS discount_kind;
            DROP TYPE IF EXISTS discount_status;
            DROP TYPE IF EXISTS sales_channel;
            """
        )
        # -- Costs & cancellation
        , migrations.RunSQL(
            """
            DO $$ BEGIN
                CREATE TYPE custom_cost_mode AS ENUM ('fixed','percent');
                CREATE TYPE custom_cost_applies_to AS ENUM ('per_cabin','per_pax');
                CREATE TYPE cancellation_charge_type AS ENUM ('percent_total','percent_cos','fixed_amount');
            EXCEPTION WHEN duplicate_object THEN NULL; END $$;
            """,
            reverse_sql="""
            DROP TYPE IF EXISTS custom_cost_mode;
            DROP TYPE IF EXISTS custom_cost_applies_to;
            DROP TYPE IF EXISTS cancellation_charge_type;
            """
        )
    ]
