# Generated by Django 5.2.6 on 2025-09-20 20:42

from django.db import migrations
from django.contrib.postgres.operations import CryptoExtension, CITextExtension, BtreeGistExtension


class Migration(migrations.Migration):
    """Prerequisites & Extensions"""

    dependencies = [
        ('common', '0001_pg_enumerated_types'),
    ]

    operations = [
        CryptoExtension(),     # -- gen_random_uuid()
        CITextExtension(),     # -- case-insensitive email
        BtreeGistExtension(),  # -- EXCLUDE (uuid WITH =) + ranges
    ]
