# Generated by Django 5.2.6 on 2025-09-26 00:48

from django.db import migrations


class Migration(migrations.Migration):
    """Seed initial data into the database."""

    dependencies = [
        ('common', '0002_pg_enumerated_types'),
        ('reports', '0001_initial'),
    ]

    operations = [
        # -- Roles
        migrations.RunSQL(
            """
            INSERT INTO roles(name, description) VALUES
                ('Admin','Full access'),
                ('Pricing Manager','Manage pricing & discounts'),
                ('Sales','Reserve & book'),
                ('Operations','Ships, routes, sailings'),
                ('Read-only','View only')
            ON CONFLICT DO NOTHING;
            """,
            reverse_sql="""
            DELETE FROM roles
                WHERE name IN ('Admin','Pricing Manager','Sales','Operations','Read-only');
            """
        ),
        # -- Permissions (sample; expand as needed)
        migrations.RunSQL(
            """
            INSERT INTO permissions(key, description) VALUES
                ('realtime.subscribe','Subscribe to realtime WS'),
                ('lock.override','Override collaborative locks'),
                ('pricing.override_margin','Override default margins'),
                ('discount.activate','Activate or deactivate discounts')
            ON CONFLICT DO NOTHING;
            """,
            reverse_sql="""
            DELETE FROM permissions
                WHERE key IN ('realtime.subscribe','lock.override','pricing.override_margin','discount.activate');
            """
        ),
        # -- Cabin categories
        migrations.RunSQL(
            """
            INSERT INTO cabin_categories(name, sort_order) VALUES
                ('Inside',10),('Oceanview',20),('Balcony',30),('Suite',40),('Deluxe',50),('Premium',60)
            ON CONFLICT DO NOTHING;
            """,
            reverse_sql="""
            DELETE FROM cabin_categories
                WHERE name IN ('Inside','Oceanview','Balcony','Suite','Deluxe','Premium');
            """
        ),
        # -- Reserve settings (default)
        migrations.RunSQL(
            """
            INSERT INTO reserve_settings(id) VALUES (gen_random_uuid())
            ON CONFLICT DO NOTHING;
            """,
            # Can't be reversed since UUID is generated (no specific WHERE clause possible)
        ),
    ]
