# Generated by Django 5.2.6 on 2025-09-10 02:42

import django.contrib.postgres.functions
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('place_id', models.TextField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tz', models.TextField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('route', 'seq'), name='unique_route_seq')],
            },
        ),
    ]
