# Generated by Django 5.2.6 on 2025-09-20 15:20

import common.functions
import django.contrib.postgres.functions
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_enable_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('created_at', models.DateTimeField(db_default=common.functions.TxNow())),
                ('updated_at', models.DateTimeField(db_default=common.functions.TxNow())),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('place_id', models.TextField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tz', models.TextField(null=True)),
            ],
            options={
                'db_table': 'route_legs',
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='route',
            trigger=pgtrigger.compiler.Trigger(name='trg_routes_updated', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                NEW.updated_at := NOW();\n                RETURN NEW;\n            END;\n            ', hash='26c19252e10dce2934c2f34a6816ad1d9632ac33', operation='UPDATE', pgid='pgtrigger_trg_routes_updated_c50a5', table='routes', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='routeleg',
            name='route',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='routes.route'),
        ),
        migrations.AddConstraint(
            model_name='routeleg',
            constraint=models.UniqueConstraint(fields=('route', 'seq'), name='route_legs_route_id_seq_key'),
        ),
    ]
