# Generated by Django 5.2.6 on 2025-09-10 03:07

import django.contrib.postgres.functions
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('operator', models.TextField()),
                ('contact_person', models.TextField()),
                ('address', models.JSONField()),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ShipAmenity',
            fields=[
                ('pk', models.CompositePrimaryKey('ship_id', 'amenity_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogs.amenity')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships_cabins.ship')),
            ],
        ),
        migrations.AddField(
            model_name='ship',
            name='amenities',
            field=models.ManyToManyField(related_name='ship_amenities', through='ships_cabins.ShipAmenity', to='catalogs.amenity'),
        ),
        migrations.CreateModel(
            name='ShipCurrency',
            fields=[
                ('currency', models.CharField(max_length=3)),
                ('pk', models.CompositePrimaryKey('ship_id', 'currency', blank=True, editable=False, primary_key=True, serialize=False)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships_cabins.ship')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='currency_format_check')],
            },
        ),
    ]
