# Generated by Django 5.2.6 on 2025-09-10 11:18

import django.contrib.postgres.functions
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('ships_cabins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('number', models.TextField()),
                ('deck', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogs.cabincategory')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ships_cabins.ship')),
            ],
        ),
        migrations.CreateModel(
            name='CabinMap',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=8)),
                ('svg_url', models.TextField()),
                ('raster_url', models.TextField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ships_cabins.ship')),
            ],
        ),
        migrations.CreateModel(
            name='CabinMapZone',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False)),
                ('polygon', models.JSONField()),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ships_cabins.cabin')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships_cabins.cabinmap')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cabin',
            constraint=models.UniqueConstraint(fields=('ship', 'number'), name='unique_ship_number'),
        ),
        migrations.AddConstraint(
            model_name='cabinmap',
            constraint=models.UniqueConstraint(fields=('ship', 'version'), name='unique_ship_version'),
        ),
    ]
