# Generated by Django 5.2.6 on 2025-09-11 12:00

import django.contrib.postgres.functions
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships_cabins', '0002_cabin_cabinmap_cabinmapzone_cabin_unique_ship_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='id',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='is_archived',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cabinmap',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cabinmap',
            name='id',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cabinmap',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_default='draft', default='draft', max_length=8),
        ),
        migrations.AlterField(
            model_name='cabinmap',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cabinmapzone',
            name='id',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ship',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ship',
            name='id',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=django.contrib.postgres.functions.RandomUUID, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ship',
            name='is_archived',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='ship',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
    ]
