# Generated by Django 5.2.6 on 2025-09-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships_cabins', '0003_alter_cabin_created_at_alter_cabin_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shipcurrency',
            name='currency_format_check',
        ),
        migrations.AddConstraint(
            model_name='shipcurrency',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='ship_currency_format_check'),
        ),
    ]
