# Generated by Django 5.2.6 on 2025-09-26 00:46

import common.functions
import django.contrib.postgres.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Should be depending on FX & Prefs migrations
        ('selling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('entity', models.TextField()),
                ('entity_id', models.UUIDField(null=True)),
                ('action', models.TextField()),
                ('before', models.JSONField(null=True)),
                ('after', models.JSONField(null=True)),
                ('ts', models.DateTimeField(db_default=common.functions.TxNow())),
                ('actor', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='idx_audit_entity')],
            },
        ),
    ]
