# Generated by Django 5.2.6 on 2025-09-27 15:10

import common.functions
import django.contrib.postgres.functions
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(db_default=common.functions.TxNow())),
                ('updated_at', models.DateTimeField(db_default=common.functions.TxNow())),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('pk', models.CompositePrimaryKey('role_id', 'perm_key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('perm_key', models.ForeignKey(db_column='perm_key', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='myadmin.permission')),
                ('role', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='myadmin.role')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='role_permissions', through='myadmin.RolePermission', to='myadmin.permission'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'role_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='myadmin.role')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='user_roles', through='myadmin.UserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('name',), name='roles_name_key'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='role',
            trigger=pgtrigger.compiler.Trigger(name='trg_roles_updated', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                NEW.updated_at := NOW();\n                RETURN NEW;\n            END;\n            ', hash='bf530f4f1c3d557f0b85d499e636e20201611817', operation='UPDATE', pgid='pgtrigger_trg_roles_updated_eb838', table='roles', when='BEFORE')),
        ),
    ]
