# Generated by Django 5.2.7 on 2025-10-06 05:46

import common.fields
import common.functions
import django.contrib.postgres.functions
import django.db.models.deletion
import myauth.models
import pgtrigger.compiler
import pgtrigger.migrations
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_pg_enumerated_types'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), primary_key=True, serialize=False)),
                ('email', models.EmailField(db_collation='case_insensitive', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('twofa_enabled', models.BooleanField(db_default=True)),
                ('twofa_method', models.TextField(choices=[('sms', 'SMS'), ('totp', 'TOTP')], db_default='sms', null=True)),
                ('status', common.fields.PostgresEnumField(choices=[('active', 'Active'), ('suspended', 'Suspended')], db_default='active', enum_type='user_status')),
                ('designation', models.TextField(null=True)),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField(null=True)),
                ('last_name', models.TextField()),
                ('created_at', models.DateTimeField(db_default=common.functions.TxNow())),
                ('updated_at', models.DateTimeField(db_default=common.functions.TxNow())),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', myauth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fx_mode', models.TextField(choices=[('manual', 'Manual'), ('live', 'Live')], db_default='manual')),
                ('notify_cabin_avail', models.BooleanField(db_default=True)),
                ('notify_flash_sale', models.BooleanField(db_default=True)),
            ],
            options={
                'db_table': 'user_prefs',
                'constraints': [models.CheckConstraint(condition=models.Q(('fx_mode__in', ['manual', 'live'])), name='user_prefs2_fx_mode_check')],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('phone',), name='users_phone_key'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='users_email_key'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('twofa_method__in', ['sms', 'totp'])), name='users_twofa_method_check'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='trg_users_updated', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            BEGIN\n                NEW.updated_at := NOW();\n                RETURN NEW;\n            END;\n            ', hash='14fbe98ab39aa7d9bc165478b76dcb73a461f5ab', operation='UPDATE', pgid='pgtrigger_trg_users_updated_cc0cc', table='users', when='BEFORE')),
        ),
    ]
